/* eslint-disable */
// Generated by Wrangler by running `wrangler types db/worker-configuration.d.ts --include-runtime false --strict-vars false` (hash: 485f6ea4d69697f664b4e1e3e6d31a00)
interface __BaseEnv_Env {
	DB: D1Database;
	OWNER_EMAIL: string;
	SITE_ORIGIN: string;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "OWNER_EMAIL" | "SITE_ORIGIN">> {}
}
